name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Instalar dependências do sistema
      run: |
        sudo apt update
        sudo apt install -y libffi-dev libssl-dev libsqlite3-dev zlib1g-dev \
                            autoconf automake build-essential libtool pkg-config \
                            unzip openjdk-17-jdk git wget

    - name: Instalar Buildozer
      run: |
        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Construir APK
      run: |
        buildozer android debug

    - name: Fazer upload do APK como artefato
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
